name = "Newb X Horizon"
version = [0, 15, 0]
min_supported_mc_version = [1, 20, 80]
url = "https://github.com/1Sekon/newb-x-horizon/"
authors = ["1Sekon", "devendrn"]
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Actor"]

[description]
# %w = patch warning, %v = version
long = '''
§c%w
§7- A newb shader variant wirh a simple enhancement
%v
§3https://github.com/1Sekon/newb-x-horizon/
'''
short = "Variant of Newb Shader for RenderDragon"

[uuid] # Use https://www.uuidgenerator.net/version4
header = "8f93cb2d-7a4f-4e30-a506-67c7af9a56a3"
module = "b16c3d83-07cc-40ef-87f0-c46738733ae3"

[info]
# %a = authors
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
'''
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "NO_WAVE_NO_FOG"
materials = ["RenderChunk"]
description = '''
§lNo Fog and Wave§r\n - Disable fog with no plants and water effects
'''

[[subpack]]
define = "NO_FOG"
materials = ["RenderChunk"]
description = '''
§lNo Fog
'''

[[subpack]]
define = "NO_WPWAVE"
materials = ["RenderChunk"]
description = '''
§lNo Wave§r\n - Disable plants and water wave effects
'''

[[subpack]]
define = "NEW_AURORA"
materials = ["RenderChunk", "Sky", "Clouds"]
description = '''
§lNew Aurora§r\n - New aurora style for vanilla clouds
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
§lDefault
'''
